### ISSUE TITLE
`On.HealthManager.HPScaleGG.GetScaledHP` unhookable

### ISSUE THREAD

**Issue by Clazex** [hk-modding/api#88] opened 2021-11-28 14:19 UTC
Seems to be a type mismatch.

```plain
[ERROR]:[API] - System.Reflection.TargetInvocationException: Exception has been thrown by the target of an invocation. ---> System.InvalidOperationException: Parameter #0 of hook for Int32 GetScaledHP(Int32) doesn't match, must be HealthManager+HPScaleGG& or related
[ERROR]:[API] -   at MonoMod.RuntimeDetour.Hook..ctor (System.Reflection.MethodBase from, System.Reflection.MethodInfo to, System.Object target, MonoMod.RuntimeDetour.HookConfig& config) [0x001d6] in <beff6d47b190417a8587e20bb59e36bb>:0 
[ERROR]:[API] -   at MonoMod.RuntimeDetour.Hook..ctor (System.Reflection.MethodBase from, System.Reflection.MethodInfo to, System.Object target, MonoMod.RuntimeDetour.HookConfig config) [0x00000] in <beff6d47b190417a8587e20bb59e36bb>:0 
[ERROR]:[API] -   at MonoMod.RuntimeDetour.Hook..ctor (System.Reflection.MethodBase from, System.Reflection.MethodInfo to, System.Object target) [0x0001d] in <beff6d47b190417a8587e20bb59e36bb>:0 
[ERROR]:[API] -   at MonoMod.RuntimeDetour.Hook..ctor (System.Reflection.MethodBase method, System.Delegate to) [0x0000e] in <beff6d47b190417a8587e20bb59e36bb>:0 
[ERROR]:[API] -   at MonoMod.RuntimeDetour.HookGen.HookEndpoint._NewHook (System.Reflection.MethodBase from, System.Delegate to) [0x00000] in <beff6d47b190417a8587e20bb59e36bb>:0 
[ERROR]:[API] -   at MonoMod.RuntimeDetour.HookGen.HookEndpoint._Add[TDelegate] (System.Func`3[T1,T2,TResult] gen, TDelegate hookDelegate) [0x0003c] in <beff6d47b190417a8587e20bb59e36bb>:0 
[ERROR]:[API] -   at MonoMod.RuntimeDetour.HookGen.HookEndpoint.Add (System.Delegate hookDelegate) [0x00000] in <beff6d47b190417a8587e20bb59e36bb>:0 
[ERROR]:[API] -   at MonoMod.RuntimeDetour.HookGen.HookEndpointManager.Add (System.Reflection.MethodBase method, System.Delegate hookDelegate) [0x00028] in <beff6d47b190417a8587e20bb59e36bb>:0 
[ERROR]:[API] -   at MonoMod.RuntimeDetour.HookGen.HookEndpointManager.Add[T] (System.Reflection.MethodBase method, System.Delegate hookDelegate) [0x00000] in <beff6d47b190417a8587e20bb59e36bb>:0 
[ERROR]:[API] -   at On.HealthManager+HPScaleGG.add_GetScaledHP (On.HealthManager+HPScaleGG+hook_GetScaledHP ) [0x0000a] in <915008e642024ad18ef4886ccc1a1bd3>:0 
```

**Comment by RedFrog6002** [comment] 2021-12-13 14:18
Could you provide the code causing this? This seems to be a problem with MonoMod.RuntimeDetour.HookGen since that’s what generates the On and IL namespaces

**Comment by mandar1jn** [comment] 2021-12-14 13:47
It might also be worth updating the monomod package. It seems to be around 7 months old

**Comment by flibber-hk** [comment] 2021-12-15 00:59
@RedFrog6002 it's trivial to replicate this; you can just try

```cs
private int HPScaleGG_GetScaledHP(On.HealthManager.HPScaleGG.orig_GetScaledHP orig, ref ValueType self, int originalHP)
{
  return orig(ref self, originalHP);
}
```

The problem is that HealthManager.HPScaleGG is a private struct, i.e. not accessible to mods, struct self is always passed by reference and ref structs aren't compatible even if one inherits from the other (the issue doesn't seem to be resolved in the latest release). 

I suppose it's really a bug in HookGen, although IMO the issue is really that it's false advertising to provide this hook in the first place. It would be possible to create your own hook, but you couldn't do it with Hook I don't think (you'd have to do a Detour) and it'd be quite annoying. That said there are a few not-too-hard fixes you could do, either IL hook HPScaleGG, or On/IL hook HealthManager.Start (because that's the only place where GetScaledHP is used).

**Comment by mandar1jn** [comment] 2021-12-15 06:12
Okay. So this is something that should be reported to monomod

**Closed** 2021-12-15 10:11 UTC
